### ISSUE TITLE
database connection failure

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#95]
One of our hackers can't connect to the database after running docker-compose up.  It's not clear why.  The db container looks like it's launching fine, and we haven't done changed any environment settings.

annotations_1           | Traceback (most recent call last):
annotations_1           |   File "src/pymssql/_pymssql.pyx", line 646, in pymssql._pymssql.connect
annotations_1           |   File "src/pymssql/_mssql.pyx", line 2108, in pymssql._mssql.connect
annotations_1           |   File "src/pymssql/_mssql.pyx", line 701, in pymssql._mssql.MSSQLConnection.__init__
annotations_1           | pymssql._mssql.MSSQLDriverException: Connection to the database failed for an unknown reason.

**Comment by simra** [comment]
I learned from the dev that she's using a mac, so that's probably the root cause. If I get a chance I'll try to troubleshoot on a mac.  I validated on another linux machine and it's working fine.
